name: Validate
description: Check for dead links

runs:
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Checkout global antora-playbook
      uses: actions/checkout@v4
      with:
        repository: hazelcast/hazelcast-docs
        sparse-checkout: antora-playbook.yml lib/api_json.js
        sparse-checkout-cone-mode: false
        path: hazelcast-docs
        ref: main

    - name: Check for broken internal links
      run: |
        cp "./hazelcast-docs/lib/api_json.js" "./api_json.js"
        npm i
        npm i -D yaml@2.6.0
        node load-check-links-playbook.js $GITHUB_REPOSITORY $GITHUB_BASE_REF
        ./node_modules/.bin/antora --fetch --to-dir test --log-level=error --log-failure-level=error --extension=@jcahills/antora-link-checker check-links-playbook.yml
