# This workflow will take the contents of the content branches and build the production documentation site

name: Build production site

on:
  push:
    branches: [ main, 'v/*', archived-versions ]
  workflow_call:

jobs:
  deploy:
    runs-on: ubicloud-standard-2
    steps:
      - name: Dispatch docs deployment
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6001915875dde5f2ff105296

