# This workflow will take the contents of the content branches and build the production documentation site

name: Build production site

on:
  push:
    branches: [ main, 'v/*', archived-versions ]

jobs:
  dispatch:
    uses: ./.github/workflows/deploy-docs-workflow.yml

