name: Test external links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1" # Runs at 12:00, only on Monday
     
jobs:
  test-external-links:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: hazelcast/hz-docs/.github/actions/test-external-links@main
        with:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DOCS }}
