name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Checkout Actions
        uses: actions/checkout@v4
        with:
          repository: hazelcast/hazelcast-docs
          path: hazelcast-docs
          ref: main
      - name: Check dead links
        uses: ./hazelcast-docs/.github/actions/validate
