name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v4
      - name: Checkout Common Files
        uses: actions/checkout@v4
        with:
          repository: fantkolja/hazelcast-docs
          sparse-checkout: |
            .github/actions/validate@1/action.yml
            antora-playbook.yml
            lib/load-check-links-playbook.js
          sparse-checkout-cone-mode: false
          path: hazelcast-docs
          ref: feature/common-dead-links-checker
      - name: Check dead links
        uses: ./hazelcast-docs/.github/actions/validate
