# This workflow will check if the incoming pull request includes any broken links

name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Checkout global antora-playbook
      uses: actions/checkout@v4
      with:
        repository: hazelcast/hazelcast-docs
        sparse-checkout: antora-playbook.yml
        sparse-checkout-cone-mode: false
        path: hazelcast-docs
        ref: main

    - name: Check for broken internal links
      run: |
        npm i
        npm i -D yaml@2.6.0
        node load-check-links-playbook.js $GITHUB_REPOSITORY $GITHUB_BASE_REF
        ./node_modules/.bin/antora --fetch --to-dir test --log-level=error --log-failure-level=error --extension=@jcahills/antora-link-checker check-links-playbook.yml
