# This workflow will check if the incoming pull request includes any broken links

name: Check for dead links

on:
  pull_request:
    branches: [main, 'v/*', archived-versions]
  workflow_dispatch:

jobs:
  check-links:

    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/validate
